
language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g polymer-cli
  - npm install -g bower
  - bower install

script:
  - polymer build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
    slack: ngvikings:zQoPZukTb2HbPBn4bbdXWTB4
